# Generated by Django 3.1.5 on 2022-01-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('M_no', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('reg_date', models.DateField(auto_now=True, null=True)),
                ('img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='SellerImage')),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
